server.port=8081
spring.application.name=order-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Resilience4j Circuit Breaker Ayarlar?
resilience4j.circuitbreaker.instances.inventory.slidingWindowSize=5
resilience4j.circuitbreaker.instances.inventory.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventory.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.inventory.permittedNumberOfCallsInHalfOpenState=3
# E?er bir istek 3 saniyeden uzun sürerse bunu "Yava? (Slow Call)" olarak i?aretle
resilience4j.circuitbreaker.instances.inventory.slowCallDurationThreshold=3s
# Son 5 iste?in %50'si yava?sa (3 saniyeyi geçiyorsa) zombi tehlikesi var demektir, ?alteri indir!
resilience4j.circuitbreaker.instances.inventory.slowCallRateThreshold=50
# Yüzdelik hesaba ba?lamak için en az 5 istek bekle (Varsay?lan 100 de?erini eziyoruz)
resilience4j.circuitbreaker.instances.inventory.minimumNumberOfCalls=5
